name = "EMTSim"
uuid = "4361663e-8052-47f0-9e5c-92b999e23d48"
authors = ["Hans WÃ¼rfel <git@wuerfel.io> and contributors"]
version = "0.1.0"

[deps]
BlockSystems = "4663d367-db1f-4bef-81e7-dc1bd7f7b428"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NetworkDynamics = "22e9dc34-2a0d-11e9-0de0-8588d035468b"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
SteadyStateDiffEq = "9672c7b4-1e72-59bd-8a11-6ac3964bc41f"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
BlockSystems = "0.4"
CSV = "0.10"
DataFrames = "1"
DiffEqCallbacks = "2"
Graphs = "1"
ModelingToolkit = "7,8"
NetworkDynamics = "0.7,0.8"
OrdinaryDiffEq = "6"
SteadyStateDiffEq = "1"
Unitful = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
